import React from 'react';
import { Link } from 'react-router-dom';

export const PrivacyPolicyPage = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16 space-y-6 text-slate-700 text-xs sm:text-sm leading-relaxed">
      <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900">Privacy Policy</h1>
      <p className="text-xs text-slate-500">Last updated: January 2026</p>

      <p>
        Aquasol Energy ("we", "our", or "us"), based in Chandan Nagar, Pune, values your trust and is committed to protecting your personal information. This Privacy Policy describes how we handle information collected via our website and lead enquiry forms.
      </p>

      <h3 className="text-base font-bold text-slate-900 mt-4">1. Information We Collect</h3>
      <p>
        When you submit an enquiry, calculate solar estimates, or schedule a site survey, we may collect your name, telephone number, email address, property locality, and electricity consumption details.
      </p>

      <h3 className="text-base font-bold text-slate-900 mt-4">2. Purpose of Collection</h3>
      <p>
        Your data is used strictly to prepare engineering proposals, provide customer support, schedule site inspections, and register your application on the PM Surya Ghar national portal with your authorization. We do not sell or trade your data to third-party marketing companies.
      </p>

      <h3 className="text-base font-bold text-slate-900 mt-4">3. Security</h3>
      <p>
        We employ industry-standard security practices and encryption to protect your data stored within our servers.
      </p>

      <div className="pt-6 border-t border-slate-200">
        <Link to="/" className="text-brand-blue-600 font-bold hover:underline">← Return to Homepage</Link>
      </div>
    </div>
  );
};

export const TermsPage = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16 space-y-6 text-slate-700 text-xs sm:text-sm leading-relaxed">
      <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900">Terms & Conditions</h1>
      <p className="text-xs text-slate-500">Last updated: January 2026</p>

      <p>
        By using this website, you agree to comply with the terms and conditions outlined below. All solar product specifications, warranties, and installations are governed by formalized commercial contracts issued by Aquasol Energy.
      </p>

      <h3 className="text-base font-bold text-slate-900 mt-4">1. Solar Estimates & Quotations</h3>
      <p>
        Output values generated by our online solar calculator and web pages are engineering approximations based on average Maharashtra insolation data and MSEDCL tariffs. Final system sizing, output, and pricing are confirmed following a physical on-site technical inspection.
      </p>

      <h3 className="text-base font-bold text-slate-900 mt-4">2. Government Schemes & Subsidies</h3>
      <p>
        Central subsidies under PM Surya Ghar are subject to national ministry guidelines, technical feasibility clearance, and DISCOM net-metering approvals. Aquasol Energy coordinates the application process as an authorized vendor.
      </p>

      <div className="pt-6 border-t border-slate-200">
        <Link to="/" className="text-brand-blue-600 font-bold hover:underline">← Return to Homepage</Link>
      </div>
    </div>
  );
};

export const DisclaimerPage = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16 space-y-6 text-slate-700 text-xs sm:text-sm leading-relaxed">
      <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900">Disclaimer</h1>
      <p className="text-xs text-slate-500">Last updated: January 2026</p>

      <p>
        Aquasol Energy is a private renewable energy solutions provider and authorized solar vendor registered under MSME in Pune, Maharashtra.
      </p>

      <h3 className="text-base font-bold text-slate-900 mt-4">PM Surya Ghar Scheme Distinction</h3>
      <p>
        Aquasol Energy is not a government ministry or statutory electricity board. We provide professional engineering, procurement, installation, and liaison services assisting residential consumers to avail benefits under the central government's PM Surya Ghar Muft Bijli Yojana. Official scheme details and direct portal access can be found at <a href="https://pmsuryaghar.gov.in" target="_blank" rel="noreferrer" className="text-brand-blue-600 underline">pmsuryaghar.gov.in</a>.
      </p>

      <div className="pt-6 border-t border-slate-200">
        <Link to="/" className="text-brand-blue-600 font-bold hover:underline">← Return to Homepage</Link>
      </div>
    </div>
  );
};
